-- AlterTable
ALTER TABLE "Form" ADD COLUMN     "image" TEXT,
ADD COLUMN     "lastOpened" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
